import Location from './Location';
import ProfileImage from './ProfileImage';
import UserAbstract from './UserAbstract';
import UserMedal from './UserMedal';

export default interface User extends UserAbstract {
  alias: string;
  ark_published_count: number;
  badge_count: number;
  book_collected_count: number;
  can_donate: boolean;
  can_set_original: boolean;
  collected_subjects_count: number;
  photo_albums_count: number;
  following_doulist_count: number;
  owned_doulist_count: number;
  followers_count: number;
  display_followers_count: string;
  following_count: number;
  dramas_count: number;
  email: string;
  enable_disturb_free: boolean;
  user_hot_module_enabled: boolean;
  enable_wishlist_notification: boolean;
  fanta_enabled: boolean;
  followed: boolean;
  gallery_topics_count: number;
  group_chat_count: number;
  has_user_hot_module: boolean;
  has_opened_archives: boolean;
  has_password: boolean;
  has_set_profile: boolean;
  in_blacklist: boolean;
  is_abnormal: boolean;
  is_banned: boolean;
  is_normal: boolean;
  is_phone_bound: boolean;
  is_phone_verified: boolean;
  is_readonly: boolean;
  is_subject_noviciate: boolean;
  is_wechat_bound: boolean;
  is_weibo_bound: boolean;
  joined_group_count: number;
  last_visit_time: string;
  listeners_count: number;
  loc_name: string;
  loc: Location;
  medal_groups: UserMedal[];
  message_count: number;
  movie_collected_count: number;
  music_collected_count: number;
  need_community_exam: boolean;
  niffler_columns_count: number;
  notes_count: number;
  notifications: string;
  owned_events_count: number;
  phone_number: string;
  profile_banner: ProfileImage;
  readonly_message: string;
  readers_count: number;
  reg_time: string;
  remark: string;
  reviews_count: number;
  show_audience_count: boolean;
  show_cart: boolean;
  show_fanta: boolean;
  statuses_count: number;
  subscribe_niffler_columns_count: number;
  tags_count: number;
  total_reviews: number;
  total_wish: number;
  verify_name: string;
  verify_roles: string[],
  verify_works_count: number;
  viewers_count: number;
  wechat_name: string;
  weibo_name: string;
}
